apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  labels:
    app: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: project
        image: project123devops/myapp:latest
        ports:
        - containerPort: 3000
